require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/unidades", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Unidade. As you add validations to Unidade, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Unidade.create! valid_attributes
      get unidades_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      unidade = Unidade.create! valid_attributes
      get unidade_url(unidade)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_unidade_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      unidade = Unidade.create! valid_attributes
      get edit_unidade_url(unidade)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Unidade" do
        expect {
          post unidades_url, params: { unidade: valid_attributes }
        }.to change(Unidade, :count).by(1)
      end

      it "redirects to the created unidade" do
        post unidades_url, params: { unidade: valid_attributes }
        expect(response).to redirect_to(unidade_url(Unidade.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Unidade" do
        expect {
          post unidades_url, params: { unidade: invalid_attributes }
        }.to change(Unidade, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post unidades_url, params: { unidade: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested unidade" do
        unidade = Unidade.create! valid_attributes
        patch unidade_url(unidade), params: { unidade: new_attributes }
        unidade.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the unidade" do
        unidade = Unidade.create! valid_attributes
        patch unidade_url(unidade), params: { unidade: new_attributes }
        unidade.reload
        expect(response).to redirect_to(unidade_url(unidade))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        unidade = Unidade.create! valid_attributes
        patch unidade_url(unidade), params: { unidade: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested unidade" do
      unidade = Unidade.create! valid_attributes
      expect {
        delete unidade_url(unidade)
      }.to change(Unidade, :count).by(-1)
    end

    it "redirects to the unidades list" do
      unidade = Unidade.create! valid_attributes
      delete unidade_url(unidade)
      expect(response).to redirect_to(unidades_url)
    end
  end
end
